name: learn-github-actions
on: 
  push:
    branch:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  get-hostname:
    runs-on: self-hosted
    steps:
      - run: hostname
