name: learn-github-actions
on: 
  push:
    branch:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  get-hostname:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: test_st2_workflow.sh
